FROM ubuntu:trusty

RUN apt update
RUN apt install -y iptables

# RUN apt install -y vim openjdk-8-jdk ca-certificates openjdk-8-jdk pkg-config gcc make ant g++ maven git libboost-dev libcurl4-openssl-dev libssl-dev unixodbc-dev libjson0-dev cmake libgtest-dev postgresql-9.5 postgresql-client-9.5 postgresql-client-common postgresql-contrib-9.5 odbc-postgresql cmake libgtest-dev sshpass wget

RUN apt install -y tmux screen net-tools iputils-ping

RUN apt install -y tcpdump

RUN mv /usr/sbin/tcpdump /usr/bin/tcpdump

